### ISSUE TITLE
Can not add multiple lines

### ISSUE THREAD

**Issue by HomelessPenguin** [estruyf/vsts-file-creator#10]
Hi,
Whenever I try to add multiple lines like this.

ServerIp
BrowserName

It creates\overwrites the file like this 
ServerIpBrowserName

Am I doing something wrong? Kindly let me know.

**Comment by bahadir-be** [comment]
Yes we have same issue!
I tried **<br>** tag but it didn't work. :)

**Comment by estruyf** [comment]
You should also be able to do it by adding `\n`. I'll verify why this is happening, as this is working on my end.

**Comment by estruyf** [comment]
Line breaks should work, could be the pipeline removes it. In version 6 of the tasks I have added a `verbose` setting, this allows you to see what Azure DevOps provides the task as variable values.

If it would be that line breaks are removed in the variable values, you can add your own line breaks with `\n`.

**Comment by SyedAsadRabbani** [comment]
i am still unable to add multiple lines in version 6 . Can you please help me out in it?

**Comment by bahadir-be** [comment]
Yes,I have same issue..
