### ISSUE TITLE
Would be nice to be able to browse for the file path

### ISSUE THREAD

**Issue by jsancho** [estruyf/vsts-file-creator#12]
Just like it many other built-in tasks offer a browse option, it'd be a nice addition to have a button to browse.

It really helps avoiding issues with checking that we are configuring a valid path

Sample screenshots of the "archive files" task
![image](https://user-images.githubusercontent.com/1547884/94127075-c2fa9280-fe58-11ea-985b-42d0bbac7a99.png)

![image](https://user-images.githubusercontent.com/1547884/94127416-2f759180-fe59-11ea-866b-bb50c43805f3.png)

**Comment by estruyf** [comment]
New `6.0.0` has been published and now should include this functionality.

**Comment by jsancho** [comment]
Wow, fantastic effort, really appreciate your hard work mate!
