### ISSUE TITLE
ask 'File Creator' version 6 (file-creator@6) is dependent on a Node version (10) that is end-of-life

### ISSUE THREAD

**Issue by FredTheFrench** [estruyf/vsts-file-creator#26]
I ma using you task, but for a month now I got this warning

Downloading task: file-creator (6.0.0)
##[warning]Task 'File Creator' version 6 (file-creator@6) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

Any update ?

**Comment by kotsaris** [comment]
Lovely build task. Unfortunately builds are polluted right now due to this warning.

**Comment by estruyf** [comment]
@FredTheFrench @kotsaris thanks for making me aware. I have updated the job internally to match the new guidelines.

Let me know if version 7.0.0 fixes the issue.

**Comment by FredTheFrench** [comment]
> @FredTheFrench @kotsaris thanks for making me aware. I have updated the job internally to match the new guidelines.
> 
> Let me know if version 7.0.0 fixes the issue.

@estruyf it's seems that the issue is still present

![image](https://github.com/user-attachments/assets/6771c172-b8f5-4722-8ec3-622c1aff97ac)

**Comment by estruyf** [comment]
@FredTheFrench can you test version 7.0.1?

**Comment by FredTheFrench** [comment]
Well done, it's working without warning, cheers.

**Comment by estruyf** [comment]
Thanks @FredTheFrench for verifying 🙏

**Comment by kotsaris** [comment]
Thanks!!
