### ISSUE TITLE
How to add new line??

### ISSUE THREAD

**Issue by ghden** [estruyf/vsts-file-creator#3]
I'm not sure is an issue, I put several lines in the content box and all lines shows as a single line in the output file..

Thanks

**Comment by estruyf** [comment]
This is the default VSTS multiline text field. Just did a test on my environment in VSTS and by adding the following file contents:

```
This
is
a
test
file.
```

I see the following output:
![screenshot 2018-05-07 16 37 36](https://user-images.githubusercontent.com/2900833/39707556-11ec9566-5215-11e8-8e3d-3fea946af2b0.png)

**Comment by ghden** [comment]
Yes you right if you use more or open with Notepad you will see the lines
of text in separate lines but the file actually have only LF, not de
sequence of CR/LF.. not saying is your tool here, probably is the vsts tool
strip out the CR, anyways, for some apps that requires the CR/LF
combination would be cool to have an option to to use the CR/LF as line
terminator or LF...

If you open the text file as binary or some editors like in FAR or
notepad++ you will see there is not CR..

Thanks for your reply.

Denis.

**Comment by jitterbox** [comment]
I ran into this same problem...my Angular project's **npm build** process failed after my generated file failed with the error:
"file should end with a newline"
I recommend that the option to end files with a newline character should be added...unfortunately I'm going to have to switch to a regex build task instead.

**Comment by estruyf** [comment]
@jitterbox I have added the new line functionality to the task `v3.0.0`. It is being verified by MS automated process atm, so will be available in a couple of minutes.
