### ISSUE TITLE
How to provide destination path to create the file?

### ISSUE THREAD

**Issue by irabanta** [estruyf/vsts-file-creator#4]
I tried with $(SolutionDir)temp/myfile.txt
I tried with $account/branch/temp/myfile.txt
None of them created the file in my desired path in the build workspace.
How to make it work?

Also I want to pass the content from a build custom variable. How to do it?
Thanks in advance.

**Comment by estruyf** [comment]
Could it be you use the wrong build variables? Only the following build variables are available: https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch#predefined-variables

If you want to use variables in the content, you have to use it as follows: `$(variable-name)`.

**Comment by dirtygooback** [comment]
Was working fine and after the latest update of VSTS the extension says the file was created but it never gets created. Please look into this.

**Comment by estruyf** [comment]
What is the path you use to create it?

**Comment by dirtygooback** [comment]
$(build.artifactsstagingdirectory)\ReleaseVersion.txt

**Comment by estruyf** [comment]
How did you check that the file was not created?

I just did a couple of tests, and on my environment(s) on which I tested it still works like before.

The creation task:
![screenshot 2018-06-19 16 49 30](https://user-images.githubusercontent.com/2900833/41605020-d5f2b2aa-73e0-11e8-87d8-dd878c1e8934.png)

Task to check the contents of the folder:
![screenshot 2018-06-19 16 49 04](https://user-images.githubusercontent.com/2900833/41605060-ed11a66c-73e0-11e8-9b6d-46bcc8b30541.png)

During the run:
![screenshot 2018-06-19 16 48 52](https://user-images.githubusercontent.com/2900833/41605083-fa1bd454-73e0-11e8-8be7-1e876d275ff8.png)
![screenshot 2018-06-19 16 49 04](https://user-images.githubusercontent.com/2900833/41605098-fe8bf2ee-73e0-11e8-8e0b-2c0195104908.png)

**Comment by dirtygooback** [comment]
I also get the message that the file was created but when I publish the build artifacts the file is not there.

During:
2018-06-19T13:42:51.0540788Z File path: D:\a\3\a\DataAge.PM\ReleaseFile\ReleaseVersion.txt
2018-06-19T13:42:51.0554414Z File created

Publish:
2018-06-19T13:44:11.0607880Z Upload 'D:\a\3\a' to file container: '#/477100/drop'

**Comment by estruyf** [comment]
In that case, it seems to be an issue in the publish, not in the file creation.

Do you package your build artifacts? If so, why not make it part of that same package?

**Comment by dirtygooback** [comment]
It my very well be but all I know is that it was working before the latest VSTS update and now it doesn't. No changes were made on my end. Thanks for looking into it. :)

**Comment by estruyf** [comment]
I'm sure that it worked before, might be something changed in the publish task. Hopefully you don't have to change too much to make it work again.
