### ISSUE TITLE
Add an option to skip creating file if content is empty

### ISSUE THREAD

**Issue by damianun** [estruyf/vsts-file-creator#6]
Hello,

First of all thank. you for the useful VSTS pipeline task.

I would like to request a change/feature that would allow task to skip creating file if content is empty.

Current behaviour is that the task failes with:
`##[error]Unhandled: Input required: filecontent`

<img width="716" alt="screen shot 2019-03-07 at 17 11 39" src="https://user-images.githubusercontent.com/15859041/53975544-f81b8480-40fc-11e9-99e4-53f53caac376.png">

The use case is that, I would like to generate the file with a content filled from Variable defined while queuing a new build. This variable is not mandatoryto fill and therefore making file content empty, this failing vsts-file-creator task.

Workaround: Set the pipeline to continue on task error. Not ideal, but works for now

**Comment by estruyf** [comment]
Such a functionality has now been implemented in version 5.0.0. Feel free to test it out.

![Screenshot 2019-04-19 23 33 43](https://user-images.githubusercontent.com/2900833/56445048-96555980-62fb-11e9-853d-7ffa5ab2b6a3.png)
